import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "./context/authContext";
import "./globals.css";
import BottomImage from "./components/BottomImage";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="min-h-screen">
            <div className="flex min-h-screen justify-center items-center">
              {children}
            </div>
            <div className="footer-image">
              <BottomImage />
            </div>
          </div>
          <ToastContainer />
        </AuthProvider>
      </body>
    </html>
  );
}
